### ISSUE TITLE
net.razorvine.pickle.PickleException: expected zero arguments for construction of ClassDict (for numpy.core.multiarray._reconstruct)

### ISSUE THREAD

**Issue by woshilaiceshide** [irmen/Pyrolite#39]
I've encountered the same problem as described on http://stackoverflow.com/questions/21794750/read-python-pickle-data-stream-in-android : 
"I ran tests using the various pickle protocols (0-3) and found that it fails for 0 and 1, but succeeds for 2 and 3..."

Could you help me, please?

**Comment by woshilaiceshide** [comment]
So sorry. It's just need a customized IObjectConstructor.

close it.

**Comment by timematcher** [comment]
Could you shed some light on what do you mean by customized IObject constructor? I am trying to do the same in .NET but getting the same error. here is my code:
`var stream = new FileStream(filePkl, FileMode.Open);
            Unpickler unpickler = new Unpickler();
            Object data = unpickler.load(stream);`

Appreciate your detailed response on this.
Thanks

**Comment by irmen** [comment]
@timematcher are you using numpy as well? The easiest is probably to not send numpy arrays across Pyro at all, and first convert them to regular python arrays or bytearrays. Those will be unpickled just fine without changes to your .net code. 

Otherwise you can use the `Unpickler.registerConstructor` method to teach Pyrolite about how to deserialize classes it doesn't know about.  Look in the source code for examples of how to use this.

**Comment by timematcher** [comment]
@irmen I am working with a **.PKL file** that was generated by a machine learning training algorithm/program written in python. It was provided to me  and I do not know python.

I have tried to communicate to the provider that the PKL be regenerated with custom options so that the output (pkl) file it generates should use regular arrays instead of the numpy arrays. However, I am not sure the provider has much control over this process.

Here is snapshot of what the PKL file looks internally.
![image](https://user-images.githubusercontent.com/11568346/43021147-04397f3c-8c7c-11e8-94e7-65c09ed964d3.png)

Having numpy array support would be a great thing indeed. I have seen people tryingt to use pyrolite and then giving up because it does not support numpy. I myself dont know what numpy array is and how it works and I suppose its difficult to implement and that is why it was left out,.. maybe?

**Comment by irmen** [comment]
Dumping the binary pickle file is not very helpful. Pyrolite itself doesn't know how to deserialize arbitrary numpy arrays. It only knows about Python's built-in types and datastructures (and a couple of custom types from the Pyro library). Numpy arrays are a complex beast ( https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.ndarray.html ) .

Surely you know SOMETHING about what data you're getting? 

If the provider isn't able to convert their data to basic data types first, you're going to have to do it yourself.  I think the easiest way is to learn a bit of Python and use Python itself (+numpy) to read the pickle file you have, convert it into something simpler (basic arrays or lists), and send that over to your .net program.    The other option is to write a custom class constructor and register this with pyrolite, like pointed out above. You're going to have to dive deeply into the data format of pickled numpy arrays and what is inside your dataset.

**Comment by timematcher** [comment]
@ireman I juts found out that the PKL files are actual Machine learning models generated by **SciKit learn**. I might need to look into scikit learn and see how can i generate PKL files without numpy arrays.

**Comment by irmen** [comment]
Tbh, sounds like you really should invest into getting to know a bit of Python (+SkiKit learn) to (pre) process those files.  But that's just my view
