### ISSUE TITLE
make the .net library work with .net core

### ISSUE THREAD

**Issue by irmen** [irmen/Pyrolite#42]

**Comment by ststeiger** [comment]
Mobius depends on this libary. 
If it isn't .net core ready, then Mobius can't be ported to .NET Core. 
https://github.com/Microsoft/Mobius
When Mobius can't be ported to .NET Core, Apache Spark-SQL can't be used in .NET Core.

**Comment by irmen** [comment]
Actually, I think we should focus on the .NET Standard to target...  https://docs.microsoft.com/en-us/dotnet/standard/net-standard  
Target should likely be .NET STandard v1.1 or v1.2

**Comment by ststeiger** [comment]
Yes, this is correct. 
However, I'd focus on Netstandard 2.0 instead. 
Otherwise, you'll have to make too many (pointless) changes. 
Nothing against NetStandard 1.1/1.2 however, if you have the time for that.

**Comment by irmen** [comment]
When targeting NetStandard 2.0 I'll have problems with building it with Mono on my Linux box:  Debian stretch, which is shipped with mono 4.6.  So NetStandard 1.6 is the highest, and I really wonder what shall have to be changed when aiming for 1.2?  I guess I'll find out once I get around to this. 
I suppose I have to use Visual Studio for this

**Comment by ststeiger** [comment]
No, actually JetBrains Rider will work fine on Linux. 
Just need to install the .NET Core SDK on the machine. 

https://www.microsoft.com/net/learn/get-started/linuxubuntu
sudo apt-get update
sudo apt-get install dotnet-sdk-2.0.2

Other distros - choose dropdown on site.
Well, with NetStandard 1.6 you stand a chance, since it contains reflection. 
But if you need, for example [Serializable], then you require .NET-Core 2.0+

See https://github.com/davidfowl/NetStandard/blob/master/platforms.cs

As shown here 
https://docs.microsoft.com/en-us/dotnet/standard/net-standard
for NetStandard 2.0, you'll need mono 5.4, if you want to do it with mono (which isn't required), while you probably have mono 4.6.

**Comment by irmen** [comment]
Seems Rider creates .net standard 2.0 solutions, so that will likely be the target

**Comment by ststeiger** [comment]
I'd also go with 2.0. 
Seems to be the most reasonable at the moment. 
Lower will die out anyway.

**Comment by irmen** [comment]
migrated to dotnet core and netstandard 2, there are still a bunch of compile errors in the unit tests because of the switch to mstest

**Comment by irmen** [comment]
Fixed all tests and published a 4.20 release to nuget.org   @ststeiger could you have a look if this version works for you?
