### ISSUE TITLE
Compare by value when memoizing

### ISSUE THREAD

**Issue by torokati44** [irmen/Pyrolite#55]
I ran across a use case where [this check](https://github.com/irmen/Pyrolite/blob/master/java/src/main/java/net/razorvine/pickle/Pickler.java#L218) makes me lose all benefits of memoization.
I'm pickling a data structure where a couple of fairly long strings are repeated many times, so memoizing it should make the resulting stream a lot shorter.
However, the instances are not considered equal, because they are only equal by value, not by reference. Now this doesn't necessarily matter with Strings, and maybe not for many different classes either.
So an option where the == check is removed, or replaced by a .equals call could be considered for addition in my opinion.

**Comment by torokati44** [comment]
Also, in these cases, the identityHashCode(obj) call would have to be replaced by obj.hashCode.
What do you think?

**Comment by irmen** [comment]
In your java code, I would expect that these strings were already referencing the same object (in the object graph that you're trying to serialize) ?   Any idea why that is not the case?

Regarding the identityHashcode, this was a deliberate change to improve the pickler's performance. See  #18  I'm hesitant to change it back because it may affect Spark too much

**Comment by torokati44** [comment]
They come from C++ via SWIG, this is why they are different instances. But this should not be important. Created in any way, equal strings (being immutable in Java... - and maybe not just strings, but any other immutable objects as well) should be memoized in a way that the value only occurs once in the stream in my opinion. This could reduce the output size, and maybe improve depickling performance/footprint.

**Comment by irmen** [comment]
I respectfully disagree here: checking for duplicate objects based on equality is very expensive and will not occur often in practice. So the general case suffers from a possible optimization for certain use cases.  Note that pickle itself, in Python, will also not memoize identical strings if they're not already the same object.

Is there any way you can intern these strings in your java code so that you solve the identity problem that way?

**Comment by torokati44** [comment]
I see your point, and of course, some overhead is unavoidable when checking for equivalence. It is not clear to me however, if it would be slower than computing the hash one additional time (I presume it would have to be computed anyways when inserting into the memo lookup HashMap). Many times when two objects are not equal, the check returns very early, while hash computation has to "go through" the whole content anyways.
Of course, I could easily intern the Strings, but this could be optionally done by Pyrolite as well, so it is readily available the next time someone needs it. Also, since not all objects provide a handy .intern() method, it might not be completely trivial in some cases. Simply adding an option to check for value equivalence when memoizing could work in all cases I can think of right now. And I still think this (minor?) overhead in Java could be worth it considering the stream size and depickling speed. Would have to measure it though.
I don't want to force it at all, I'm just putting my thoughts out. :)

**Comment by irmen** [comment]
Can you come up with a pull request for this perhaps? That allows us to investigate the performance properties as well.

**Comment by torokati44** [comment]
I sent the pull request, just so you can see what I was talking about. I don't consider all the changes in it to be of high enough quality for merging yet. Let me know what you think!

**Comment by torokati44** [comment]
It's been over a month now. Did anyone have a chance to take a look at my PR?

**Comment by irmen** [comment]
no, I haven't yet looked at it but thank you for the heads-up. I'll try to evaluate it shortly

**Comment by irmen** [comment]
@torokati44 well I've looked at the code and I like it! Thanks for taking the time to make it configurable and adding a test example.  I'm kinda surprised by the results to be honest.  The regular hashCode() seems just a tiny bit slower in the worst case scenario than the identityHashcode, and using your changes the pickling speed actually improves a lot in a happy scenario because the pickle stream is a lot smaller.

I'm actually considering getting rid of the identityHashcode now that I learned this... but still, I only did a tiny test

**Comment by torokati44** [comment]
Thanks! Well, without `identityHash()`, storing and reconstructing the **exact same** object hierarchy won't be possible of course. I don't need this personally (since the result will still be "equivalent", as far as `.equals()` is concerned, and for plain data it's perfectly fine), but I thought it was done this way because having this capability was a requirement. In the end, your project, your decision. :)

**Comment by irmen** [comment]
No, there's no such requirement. The reason to use identityHash was because of the pull request mentioned above where it seemed to give a reasonable performance gain in Spark

**Comment by irmen** [comment]
@mengxr do you see any issues of reverting back to regular hashCode() in light of the discussion above?

**Comment by irmen** [comment]
@torokati44 I went ahead and merged your changes. The compare by value is now also the default again for the pickler. When people want to revert to object identity comparison they can do so via the new constructor parameter for the Pickler class

**Comment by torokati44** [comment]
Thank you!
Is it really the default? The inline field initializer indeed says `=true`, but when the unary constructor delegates to the binary one, it passes the `false` as `valueCompare`. IIRC that will override the inline default. This inconsistency can be misleading.
Also, I just now noticed that I misspelled the word 'Also' in the comment of the valueCompare field...

**Comment by irmen** [comment]
Hmm, I changed it to true?:

https://github.com/irmen/Pyrolite/blob/b05daacfa464fa5d51a0c8b672721b8da26744fc/java/src/main/java/net/razorvine/pickle/Pickler.java#L109

**Comment by torokati44** [comment]
Oh, yes, you did. I was looking at my original commit, sorry.
It's too late around here, and GitHub UI wasn't entirely obvious about the fact that you altered it.
And I guess I can live with that comment typo, it's not the end of the world.
